alias config="cd ~/Documents/Configuration"
alias snarveier="vim ~/Documents/Configuration/bash/bash_aliases && source ~/Documents/Configuration/bash/bash_aliases"

alias povm="cd ~/Documents/SIC-POVM"
alias qft="cd ~/Dropbox/Skole/Studier/UiO/7.semester/FYS4170"

alias code="cd ~/Documents/interesting_code"
alias scripts="cd ~/Documents/scripts"
alias ft="cd ~/Documents/FalmaarTools"

alias faktura="cd ~/Dropbox/Falmår\ Undervisning/Faktura"

alias jn="jupyter notebook ."
alias ntg="cd ~/Dropbox/Skole/NTG/Matte\ 1T/Matte\ 1T\ 22-23"
alias 1tsync="rsync -av --delete /home/vegard/Dropbox/Skole/NTG/Matte\ 1T/Matte\ 1T\ 22-23/Undervisningsmateriell\ 1T\ 22-23/ /home/vegard/Teams/Undervisningsmateriell_1T_22-23 && onedrive --confdir=\"~/.config/SharePoint_Undervisningsmateriell_1T_22-23\" --synchronize"
alias 2psync="onedrive --confdir=\"~/.config/SharePoint_Undervisningsmateriell_2P_22-23\" --synchronize"

alias xclip="xclip -selection c"
alias l="ls -l"
