alias config="cd ~/Git/Configuration"
alias snarveier="vim ~/Git/Configuration/bash/bash_aliases && source ~/Git/Configuration/bash/bash_aliases"

alias povm="cd ~/Documents/SIC-POVM"

alias code="cd ~/Git/interesting_code"
alias scripts="cd ~/Git/scripts"

alias faktura="cd ~/Dropbox/Falmår\ Undervisning/Faktura"


alias jn="jupyter notebook ."

# alias 1tsync="onedrive --confdir=\"~/.config/Undervisningsmateriell_1T_22-23\" --synchronize && rsync -av --delete --exclude 'Undervisningsvideoer*' /home/vegard/Teams/Undervisningsmateriell_1T_22-23/ /home/vegard/Dropbox/Skole/NTG/Matte\ 1T/Matte\ 1T\ 22-23/Undervisningsmateriell\ 1T\ 22-23"

# alias 2psync="onedrive --confdir=\"~/.config/Undervisningsmateriell_2P_22-23\" --synchronize"


alias xclip="xclip -selection c"
alias l="ls -l"
